# @package _global_

# 是否启用调试模式
debug: false

# 默认绘图配置
defaults:
  - _self_
  - plot: experiment_comparison

plot:
  experiments_number: 10

# 全局样式设置
style:
  figsize: [10, 6]
  font_size: 20
  style: "seaborn-v0_8-whitegrid"

# 图表输出设置
output:
  render_mode: "plot" # 'plot', 'svg', 'png', 或 'pdf'
  save_path: "./plots"
  dpi: 300

# 实验目录和数据设置
data:
  base_dir: "./experiments/JPC/d3rlpy_logs/"
  offline_value: 3000 # 离线学习的默认返回值
